### ISSUE TITLE
Update branch name in example workflow file from "master" to "main"

### ISSUE THREAD

**Issue by nbasham-grin** [colis/action-deploy-to-wpengine#1]
First off, thanks for sharing this action, I'm testing it now and think it will work well for a couple of my upcoming projects.

This small thing tripped me up when configuring my workflow file – looks like you've updated your primary branch name from "master" to "main", but the example workflow file _uses_ line is still set to `colis/action-deploy-to-wpengine@master`.

Just wanted to mention that for others looking to base their workflow off this action. Thanks!

**Comment by colis** [comment]
@nbasham-grin fixed, thanks for catching that!
